version: '3.7'

services:
  caddy:
    restart: unless-stopped
    image: caddy:2.2.1-alpine
    volumes:
      - caddy_data:/data
      - caddy_config:/config

  postgres:
    restart: unless-stopped
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '127.0.0.1:5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    restart: unless-stopped
    image: redis
    ports:
      - '127.0.0.1:6379:6379'

  app:
    build: .
    environment:
      - POSTGRES_HOST=postgres
      - REDIS_HOST=redis
    volumes:
      - .:/app:ro
      - ./frontend/.docker.yarnrc:/app/frontend/.yarnrc:ro
      - /app/frontend/node_modules # ignore host node_modules
    ports:
      - '127.0.0.1:8000:8000' # django
    depends_on:
      - postgres
      - redis

volumes:
  caddy_data:
  caddy_config:
  pgdata:
