version: '3.7'

services:
  caddy:
    environment:
      - SERVER_HOSTNAME=checkmate.teammatehunt.com
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./Caddyfile.prod:/etc/caddy/Caddyfile
      - log_prod:/log

  app:
    restart: unless-stopped
    environment:
      - BUILD_MODE=prod
      - SERVER_ORIGIN='https://checkmate.teammatehunt.com'
    volumes:
      - build_prod:/build/backend
      - log_prod:/log

volumes:
  log_prod:
